# Generated by Django 4.0.4 on 2022-05-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('image', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(max_length=300, null=True)),
                ('Details', models.CharField(max_length=500, null=True)),
                ('maplocation', models.CharField(max_length=800, null=True)),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('ratings', models.FloatField()),
                ('phone', models.CharField(max_length=50, null=True)),
                ('Placement_Type', models.CharField(choices=[(1, 'Gas Station'), (2, 'Restaurant'), (3, 'Hotel'), (4, 'Shop')], max_length=100, null=True)),
                ('City', models.CharField(choices=[(1, 'Rabat'), (2, 'Casablanca'), (3, 'Marrackech'), (4, 'Tangier')], max_length=100, null=True)),
                ('Country', models.CharField(choices=[(1, 'Morroco'), (2, 'United States of America'), (3, 'Spain'), (4, 'France')], max_length=100, null=True)),
            ],
        ),
    ]
