# Generated by Django 4.0.3 on 2022-05-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_placement_city_alter_placement_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='City',
            field=models.CharField(choices=[('1', 'Rabat'), ('2', 'Casablanca'), ('3', 'Marrackech'), ('4', 'Tangier')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='Country',
            field=models.CharField(choices=[('1', 'Morroco'), ('2', 'United States of America'), ('3', 'Spain'), ('4', 'France')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='Placement_Type',
            field=models.CharField(choices=[('1', 'Gas Station'), ('2', 'Restaurant'), ('3', 'Hotel'), ('4', 'Shop')], max_length=100, null=True),
        ),
    ]
