# Generated by Django 4.0.3 on 2022-05-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_placement_placement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='Country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='Placement_Type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
