# Generated by Django 4.0.4 on 2022-05-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, null=True)),
                ('user_id', models.IntegerField()),
                ('rating', models.FloatField()),
                ('date_comment', models.DateTimeField(auto_now_add=True, null=True)),
                ('placement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.placement')),
                ('user_commented', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
